name: fornax-slice-testing
channels:
  - numba
  - conda-forge
dependencies:
  - python=3.9
  - astropy
  - astroquery
  - boto3
  - dustgoggles
  - fast-histogram
  - fire
  - fitsio
  - flask
  - fs
  # non-mandatory, cannot be used on non-intel-compatible architectures
  - icc_rt
  - ipython
  - jupyter
  - matplotlib
  - more-itertools
  - numba
  - numpy
  - pandas
  - photutils
  - pip
  - pyarrow
  - python-isal
  - requests
  - rich
  - scikit-learn
  - scipy
  - sh
